name: Auto Merge Approved PRs to Dev

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    if: github.event.review.state == 'approved' && github.base_ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - name: Merge PR if approved
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: 'merge'
            });
            console.log(` PR #${prNumber} merged into dev`);
